CREATE DATABASE POLYPRO
GO

USE POLYPRO
GO

IF 'NHANVIEN' IS NOT NULL
	DROP TABLE NHANVIEN
CREATE TABLE NHANVIEN
(
    MaNV NVARCHAR(20) PRIMARY KEY NOT NULL,
    MatKhau NVARCHAR(50) NOT NULL,
    HoTen NVARCHAR(50) NOT NULL,
    VaiTro BIT DEFAULT 0
)
GO

IF 'NGUOIHOC' IS NOT NULL
	DROP TABLE NGUOIHOC
CREATE TABLE NGUOIHOC
(
	MaNH NCHAR(7) PRIMARY KEY NOT NULL,
    HoTen NVARCHAR(50) NOT NULL,
    GioiTinh BIT DEFAULT 1,
    NgaySinh DATE NOT NULL,
    DienThoai NVARCHAR(24) NOT NULL,
    Email NVARCHAR(50) NOT NULL,
    GhiChu NVARCHAR(255) NULL,
    MaNV NVARCHAR(20) NOT NULL FOREIGN KEY REFERENCES NHANVIEN(MaNV),
    NgayDK DATE DEFAULT getdate()
)
GO

IF 'CHUYENDE' IS NOT NULL
	DROP TABLE CHUYENDE
CREATE TABLE CHUYENDE
(
	MaCD NCHAR(5) PRIMARY KEY NOT NULL,
	TenCD NVARCHAR(50) NOT NULL,
	HocPhi FLOAT NOT NULL,
	ThoiLuong INT NOT NULL,
	Hinh NVARCHAR(100) NOT NULL,
	MoTa NVARCHAR(255) NOT NULL
)
GO

IF 'KHOAHOC' IS NOT NULL
	DROP TABLE KHOAHOC
CREATE TABLE KHOAHOC
(
	MaKH INT PRIMARY KEY IDENTITY(1,1),
	MaCD NCHAR(5) FOREIGN KEY REFERENCES CHUYENDE (MaCD) NOT NULL,
	HocPhi FLOAT NOT NULL,
	ThoiLuong INT NOT NULL,
	NgayKG DATE NOT NULL,
	GhiChu NVARCHAR(255) NULL,
	MaNV NVARCHAR(20) FOREIGN KEY REFERENCES NHANVIEN (MaNV) NOT NULL,
	NgayTao DATE DEFAULT getdate()
)
GO

IF 'HOCVIEN' IS NOT NULL
	DROP TABLE HOCVIEN
CREATE TABLE HOCVIEN
(
	MaHV INT PRIMARY KEY IDENTITY(1,1),
	MaKH INT FOREIGN KEY REFERENCES KHOAHOC (MaKH) NOT NULL,
	MaNH NCHAR(7) FOREIGN KEY REFERENCES NGUOIHOC (MaNH) NOT NULL,
	Diem FLOAT DEFAULT -1
)
GO

ALTER TABLE HocVien  WITH CHECK ADD  CONSTRAINT FK_HocVien_KhoaHoc FOREIGN KEY(MaKH)
REFERENCES KhoaHoc (MaKH)
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE HocVien CHECK CONSTRAINT FK_HocVien_KhoaHoc
GO

ALTER TABLE HocVien  WITH CHECK ADD  CONSTRAINT FK_HocVien_NguoiHoc FOREIGN KEY(MaNH)
REFERENCES NguoiHoc (MaNH)
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE HocVien CHECK CONSTRAINT FK_HocVien_NguoiHoc
GO

ALTER TABLE KhoaHoc  WITH CHECK ADD  CONSTRAINT FK_KhoaHoc_ChuyenDe FOREIGN KEY(MaCD)
REFERENCES ChuyenDe (MaCD)
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE KhoaHoc CHECK CONSTRAINT FK_KhoaHoc_ChuyenDe
GO

ALTER TABLE KhoaHoc  WITH CHECK ADD  CONSTRAINT FK_KhoaHoc_NhanVien FOREIGN KEY(MaNV)
REFERENCES NhanVien (MaNV)
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE KhoaHoc CHECK CONSTRAINT FK_KhoaHoc_NhanVien
GO

ALTER TABLE NguoiHoc  WITH CHECK ADD  CONSTRAINT FK_NguoiHoc_NhanVien FOREIGN KEY(MaNV)
REFERENCES NhanVien (MaNV)
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE NguoiHoc CHECK CONSTRAINT FK_NguoiHoc_NhanVien
GO