CREATE DATABASE JSPSERVLETJDBC;

USE JSPSERVLETJDBC;

CREATE TABLE ROLE(
    ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    CODE VARCHAR(255) NOT NULL,
    CREATEDDATE TIMESTAMP NULL,
    MODIFIEDDATE TIMESTAMP NULL,
    CREATEDBY VARCHAR(255) NULL,
    MODIFIEDBY VARCHAR(255) NULL
);

CREATE TABLE USERS(
	ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(150) NOT NULL,
    PASSWORD VARCHAR(150) NOT NULL,
    FULLNAME VARCHAR(150) NULL,
    STATUS INT NOT NULL,
    ROLEID BIGINT NOT NULL,
    CREATEDDATE TIMESTAMP NULL,
    MODIFIEDDATE TIMESTAMP NULL,
    CREATEDBY VARCHAR(255) NULL,
    MODIFIEDBY VARCHAR(255) NULL
);

ALTER TABLE USERS ADD CONSTRAINT FK_USERS_ROLE FOREIGN KEY (ROLEID) REFERENCES ROLE(ID);

CREATE TABLE NEWS(
	ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(255) NULL,
    THUMBNAIL VARCHAR(255) NULL,
    SHORTDESCRIPTION TEXT NULL,
    CONTENT TEXT NULL,
    CATEGORYID BIGINT NOT NULL,
    CREATEDDATE TIMESTAMP NULL,
    MODIFIEDDATE TIMESTAMP NULL,
    CREATEDBY VARCHAR(255) NULL,
    MODIFIEDBY VARCHAR(255) NULL
);

CREATE TABLE CATEGORY(
	ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    CODE VARCHAR(255) NOT NULL,
    CREATEDDATE TIMESTAMP NULL,
    MODIFIEDDATE TIMESTAMP NULL,
    CREATEDBY VARCHAR(255) NULL,
    MODIFIEDBY VARCHAR(255) NULL
);

ALTER TABLE NEWS ADD CONSTRAINT FK_NEWS_CATEGORY FOREIGN KEY (CATEGORYID) REFERENCES CATEGORY(ID);

CREATE TABLE COMMENT(
	ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CONTENT TEXT NOT NULL,
    USERS_ID BIGINT NOT NULL,
    NEWS_ID BIGINT NOT NULL,
    CREATEDDATE TIMESTAMP NULL,
    MODIFIEDDATE TIMESTAMP NULL,
    CREATEDBY VARCHAR(255) NULL,
    MODIFIEDBY VARCHAR(255) NULL
);

ALTER TABLE COMMENT ADD CONSTRAINT FK_COMMENT_USERS FOREIGN KEY (USERS_ID) REFERENCES USERS(ID);
ALTER TABLE COMMENT ADD CONSTRAINT FK_COMMENT_NEWS FOREIGN KEY (NEWS_ID) REFERENCES NEWS(ID);