CREATE DATABASE SOF203LAB5
GO
USE SOF203LAB5
GO
IF OBJECT_ID('tblSTUDENT') IS NULL
CREATE TABLE tblSTUDENT
(
	MASV VARCHAR(10),
	HOTEN NVARCHAR(50),
	EMAIL VARCHAR(100),
	SDT VARCHAR(10),
	GIOITINH BIT,
	DIACHI NVARCHAR(100)
	CONSTRAINT PK_STUDENTS PRIMARY KEY (MASV)
)
GO