CREATE DATABASE TEST1
GO
USE TEST1
GO

IF OBJECT_ID('LOAIKHACHHANG') IS NULL
CREATE TABLE LOAIKHACHHANG
(
	LOAIKHACHHANG VARCHAR(20),
	TENLOAITAIKHOAN VARCHAR(20),
	CONSTRAINT PK_LOAIKHACHHANG PRIMARY KEY (LOAIKHACHHANG)
)
GO

IF OBJECT_ID('KHACHHANG') IS NULL
CREATE TABLE KHACHHANG
(
	MAKH VARCHAR(10),
	TEN NVARCHAR(50),
	SDT VARCHAR(10),
	EMAIL VARCHAR(50),
	LOAIKHACHHANG VARCHAR(20),
	CONSTRAINT PK_KHACHHANG PRIMARY KEY (MAKH),
	CONSTRAINT FK_LOAIKHACHHANG_KHACHHANG FOREIGN KEY (LOAIKHACHHANG) REFERENCES LOAIKHACHHANG
)
GO